title: Резюме Анатолий Воробьев
tagline: Инженер телекоммуникаций
logo: /assets/images/headshot_circle.png
locale: ru_RU
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
description: <br><a href="https://t.me/anatolyv99">Contact me on Telegram</a>
# remote_theme: pages-themes/cayman@v0.2.0

# remote_theme: pages-themes/architect@v0.2.0
# theme: jekyll-theme-minimal
