title: Анатолий Воробьев
logo: /assets/images/headshot_circle.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
description: <br><a href="https://t.me/anatolyv99"><img src="https://img.shields.io/badge/Telegram-blue?logo=telegram"></a>
# remote_theme: pages-themes/cayman@v0.2.0

# remote_theme: pages-themes/architect@v0.2.0
# theme: jekyll-theme-minimal
